//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #!/usr/bin/env pwsh
        ///# Copyright (c) 2023 Roger Brown.
        ///# Licensed under the MIT License.
        ///param(
        ///	$ArgumentByName = $False,
        ///	$SourceIdentifier = &apos;CancellationToken&apos;
        ///)
        ///
        ///trap
        ///{
        ///	throw $PSItem
        ///}
        ///
        ///$cancellationTokenSource = New-Object -Type System.Threading.CancellationTokenSource
        ///$cancellationTokenSource.CancelAfter(5000)
        ///$cancellationToken = $cancellationTokenSource.Token
        ///
        ///if ($ArgumentByName)
        ///{
        ///	$cancellationEvent = Register-CancellationTokenEvent -CancellationToken $cancellationToken
        ///}
        ///el [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CancellationTokenTests {
            get {
                return ResourceManager.GetString("CancellationTokenTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #!/usr/bin/env pwsh
        ///# Copyright (c) 2023 Roger Brown.
        ///# Licensed under the MIT License.
        ///param(
        ///	$ArgumentByName = $False,
        ///	$SourceIdentifier = &apos;CancellationToken&apos;
        ///)
        ///
        ///trap
        ///{
        ///	throw $PSItem
        ///}
        ///
        ///$cancellationTokenSource = New-Object -Type System.Threading.CancellationTokenSource
        ///$cancellationTokenSource.CancelAfter(5000)
        ///$cancellationToken = $cancellationTokenSource.Token
        ///
        ///if ($ArgumentByName)
        ///{
        ///	$cancellationEvent = Register-CancellationTokenEvent -CancellationToken $cancellationToken
        ///}
        ///el [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandWithCancellationTokenTests {
            get {
                return ResourceManager.GetString("CommandWithCancellationTokenTests", resourceCulture);
            }
        }
    }
}
